description: Daniel Nguyen - Designer Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://daniel-nguyen.net" # the base hostname & protocol for your site, e.g., http://yourwebsite.com

# User settings
username: Daniel Nguyen
user_description: Iâ€™m a designer driven by a passion for creating innovative and impactful solutions.  I'm always eager to explore new ideas and push the boundaries of creativity.
user_title: Designer
email: "danielnguyen@onmail.com"
youtube_username: daniel-nguyen
github_username: dansc89
blue_sky_username: daniel-nguyen.bsky.social
resume_username: "https://drive.google.com/file/d/1VwEcqkP88B4dkjsK0DNZ4-pPlyvLxu2X/view?usp=sharing"

exclude: ['package.json', 'src', 'node_modules', 'vendor']
